// src/components/ToolBar.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { ToolType } from '@/types'
import { PRESET_COLORS, MIN_LINE_WIDTH, MAX_LINE_WIDTH } from '@/types'

interface Props {
  currentTool: ToolType
  currentColor: string
  lineWidth: number
  canUndo: boolean
  canRedo: boolean
  isConnected: boolean
}

const props = defineProps<Props>()

const emit = defineEmits<{
  (e: 'update:currentTool', value: ToolType): void
  (e: 'update:currentColor', value: string): void
  (e: 'update:lineWidth', value: number): void
  (e: 'undo'): void
  (e: 'redo'): void
  (e: 'clearCanvas'): void
}>()

const tools: { type: ToolType; icon: string; label: string }[] = [
  { type: 'pen', icon: '✏️', label: '画笔' },
  { type: 'rectangle', icon: '⬜', label: '矩形' },
  { type: 'circle', icon: '⭕', label: '圆形' },
  { type: 'note', icon: '📝', label: '便利贴' }
]

const lineWidthPercent = computed(() => {
  return ((props.lineWidth - MIN_LINE_WIDTH) / (MAX_LINE_WIDTH - MIN_LINE_WIDTH)) * 100
})

function selectTool(tool: ToolType) {
  emit('update:currentTool', tool)
}

function selectColor(color: string) {
  emit('update:currentColor', color)
}

function updateLineWidth(event: Event) {
  const target = event.target as HTMLInputElement
  emit('update:lineWidth', Number(target.value))
}
</script>

<template>
  <div class="toolbar">
    <div class="toolbar-inner">
      <div class="tool-group">
        <button
          v-for="tool in tools"
          :key="tool.type"
          :class="['tool-btn', { active: currentTool === tool.type }]"
          :title="tool.label"
          @click="selectTool(tool.type)"
        >
          <span class="tool-icon">{{ tool.icon }}</span>
        </button>
      </div>

      <div class="divider"></div>

      <div class="tool-group">
        <div class="color-picker">
          <button
            v-for="color in PRESET_COLORS"
            :key="color"
            :class="['color-swatch', { active: currentColor === color }]"
            :style="{ backgroundColor: color }"
            :title="color"
            @click="selectColor(color)"
          >
            <span v-if="currentColor === color" class="check-mark">✓</span>
          </button>
        </div>
      </div>

      <div class="divider"></div>

      <div class="tool-group">
        <div class="line-width-control">
          <span class="label">粗细</span>
          <div class="slider-wrapper">
            <input
              type="range"
              :min="MIN_LINE_WIDTH"
              :max="MAX_LINE_WIDTH"
              :value="lineWidth"
              class="slider"
              @input="updateLineWidth"
            />
            <div class="slider-fill" :style="{ width: lineWidthPercent + '%' }"></div>
          </div>
          <div class="line-preview" :style="{ width: lineWidth + 'px', height: lineWidth + 'px', backgroundColor: currentColor }"></div>
        </div>
      </div>

      <div class="divider"></div>

      <div class="tool-group">
        <button
          class="action-btn"
          :class="{ disabled: !canUndo }"
          title="撤销 (Ctrl+Z)"
          @click="emit('undo')"
        >
          ↩️
        </button>
        <button
          class="action-btn"
          :class="{ disabled: !canRedo }"
          title="重做 (Ctrl+Y)"
          @click="emit('redo')"
        >
          ↪️
        </button>
        <button class="action-btn" title="清空画布" @click="emit('clearCanvas')">
          🗑️
        </button>
      </div>

      <div class="divider"></div>

      <div class="tool-group">
        <div class="connection-status" :class="{ connected: isConnected }">
          <span class="status-dot"></span>
          <span class="status-text">{{ isConnected ? '已连接' : '连接中...' }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.toolbar {
  position: fixed;
  top: 16px;
  left: 50%;
  transform: translateX(-50%);
  z-index: 100;
  padding: 0 8px;
}

.toolbar-inner {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 16px;
  background: var(--toolbar-bg);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  border: 1px solid var(--toolbar-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-md);
  animation: slideDown 0.3s ease;
}

@keyframes slideDown {
  from {
    opacity: 0;
    transform: translateY(-10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.tool-group {
  display: flex;
  align-items: center;
  gap: 4px;
}

.divider {
  width: 1px;
  height: 28px;
  background: var(--toolbar-border);
  margin: 0 4px;
}

.tool-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 40px;
  height: 40px;
  border-radius: var(--radius-md);
  background: transparent;
  transition: all var(--transition-fast);
}

.tool-btn:hover {
  background: rgba(0, 0, 0, 0.05);
}

.tool-btn.active {
  background: var(--primary-color);
  box-shadow: 0 2px 8px rgba(30, 136, 229, 0.3);
}

.tool-btn.active .tool-icon {
  filter: brightness(0) invert(1);
}

.tool-icon {
  font-size: 18px;
  line-height: 1;
}

.color-picker {
  display: flex;
  gap: 6px;
  padding: 0 4px;
}

.color-swatch {
  position: relative;
  width: 26px;
  height: 26px;
  border-radius: 50%;
  border: 2px solid transparent;
  transition: all var(--transition-fast);
}

.color-swatch:hover {
  transform: scale(1.1);
}

.color-swatch.active {
  border-color: #fff;
  box-shadow: 0 0 0 2px var(--primary-color);
}

.check-mark {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: #fff;
  font-size: 12px;
  font-weight: bold;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
}

.line-width-control {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 0 8px;
}

.label {
  font-size: 12px;
  color: var(--text-secondary);
  white-space: nowrap;
}

.slider-wrapper {
  position: relative;
  width: 100px;
  height: 4px;
}

.slider {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 4px;
  -webkit-appearance: none;
  appearance: none;
  background: transparent;
  cursor: pointer;
  z-index: 2;
}

.slider::-webkit-slider-runnable-track {
  height: 4px;
  background: #e0e0e0;
  border-radius: 2px;
}

.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: var(--primary-color);
  cursor: pointer;
  margin-top: -6px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  transition: transform var(--transition-fast);
}

.slider::-webkit-slider-thumb:hover {
  transform: scale(1.2);
}

.slider-fill {
  position: absolute;
  top: 0;
  left: 0;
  height: 4px;
  background: var(--primary-color);
  border-radius: 2px;
  pointer-events: none;
  z-index: 1;
}

.line-preview {
  border-radius: 50%;
  transition: all var(--transition-fast);
}

.action-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border-radius: var(--radius-md);
  font-size: 16px;
  transition: all var(--transition-fast);
}

.action-btn:hover:not(.disabled) {
  background: rgba(0, 0, 0, 0.05);
}

.action-btn.disabled {
  opacity: 0.3;
  cursor: not-allowed;
}

.connection-status {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 12px;
  border-radius: var(--radius-md);
  background: rgba(255, 152, 0, 0.1);
}

.connection-status.connected {
  background: rgba(67, 160, 71, 0.1);
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #ff9800;
  animation: pulse 1.5s infinite;
}

.connection-status.connected .status-dot {
  background: #43a047;
  animation: none;
}

.status-text {
  font-size: 12px;
  color: var(--text-secondary);
}
</style>

// src/components/Toolbar.tsx
import React from 'react'
import { Template, templates, generateTemplateThumbnail } from '@/utils/cutLogic'

interface ToolbarProps {
  selectedTemplate: Template | null
  onTemplateSelect: (template: Template) => void
  onUndo: () => void
  onReset: () => void
  onSave: () => void
  canUndo: boolean
}

const Toolbar: React.FC<ToolbarProps> = ({
  selectedTemplate,
  onTemplateSelect,
  onUndo,
  onReset,
  onSave,
  canUndo
}) => {
  return (
    <div className="toolbar">
      <div className="templates-section">
        <h3 className="section-title">选择模板</h3>
        <div className="templates-grid">
          {templates.map((template) => (
            <div
              key={template.id}
              className={`template-thumb ${selectedTemplate?.id === template.id ? 'selected' : ''}`}
              onClick={() => onTemplateSelect(template)}
            >
              <div className="thumb-wrapper">
                <svg
                  viewBox="0 0 400 400"
                  width="80"
                  height="80"
                  className="thumb-svg"
                  dangerouslySetInnerHTML={{ __html: template.svgPath }}
                />
              </div>
              <span className="template-name">{template.name}</span>
            </div>
          ))}
        </div>
      </div>
      
      <div className="actions-section">
        <button
          className="action-btn undo-btn"
          onClick={onUndo}
          disabled={!canUndo}
          title="撤销 (Ctrl+Z)"
        >
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M3 7v6h6"/>
            <path d="M21 17a9 9 0 0 0-9-9 9 9 0 0 0-6 2.3L3 13"/>
          </svg>
          撤销
        </button>
        
        <button
          className="action-btn reset-btn"
          onClick={onReset}
          title="重新剪刻"
        >
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/>
            <path d="M3 3v5h5"/>
          </svg>
          重新剪刻
        </button>
        
        <button
          className="action-btn save-btn"
          onClick={onSave}
          title="保存作品"
        >
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
            <polyline points="7 10 12 15 17 10"/>
            <line x1="12" y1="15" x2="12" y2="3"/>
          </svg>
          保存作品
        </button>
      </div>
      
      <style>{`
        .toolbar {
          display: flex;
          flex-direction: column;
          gap: 24px;
          padding: 20px;
          background: rgba(255, 248, 231, 0.95);
          border-radius: 12px;
          box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
          min-width: 180px;
        }
        
        .section-title {
          font-family: 'Ma Shan Zheng', cursive;
          font-size: 22px;
          color: #8b5e3c;
          margin-bottom: 12px;
          text-align: center;
          text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);
        }
        
        .templates-grid {
          display: flex;
          flex-direction: column;
          gap: 12px;
        }
        
        .template-thumb {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 6px;
          padding: 10px;
          border-radius: 8px;
          cursor: pointer;
          transition: all 0.3s ease;
          background: rgba(255, 255, 255, 0.5);
          border: 2px solid transparent;
        }
        
        .template-thumb:hover {
          transform: scale(1.1);
          border-color: #f1c40f;
          box-shadow: 0 0 15px rgba(241, 196, 15, 0.5);
        }
        
        .template-thumb.selected {
          background: rgba(241, 196, 15, 0.2);
          border-color: #f1c40f;
        }
        
        .thumb-wrapper {
          width: 80px;
          height: 80px;
          display: flex;
          align-items: center;
          justify-content: center;
          background: rgba(192, 57, 43, 0.1);
          border-radius: 6px;
        }
        
        .thumb-svg {
          opacity: 0.7;
        }
        
        .template-name {
          font-family: 'ZCOOL XiaoWei', serif;
          font-size: 14px;
          color: #5d4e37;
          white-space: nowrap;
        }
        
        .actions-section {
          display: flex;
          flex-direction: column;
          gap: 10px;
          padding-top: 16px;
          border-top: 2px solid rgba(139, 94, 60, 0.2);
        }
        
        .action-btn {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 8px;
          padding: 12px 16px;
          border: none;
          border-radius: 8px;
          font-family: 'ZCOOL XiaoWei', serif;
          font-size: 16px;
          cursor: pointer;
          transition: all 0.3s ease;
        }
        
        .action-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }
        
        .undo-btn {
          background: linear-gradient(135deg, #95a5a6, #7f8c8d);
          color: white;
        }
        
        .undo-btn:hover:not(:disabled) {
          background: linear-gradient(135deg, #7f8c8d, #6c7a7b);
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
        }
        
        .reset-btn {
          background: linear-gradient(135deg, #e74c3c, #c0392b);
          color: white;
        }
        
        .reset-btn:hover {
          background: linear-gradient(135deg, #c0392b, #a93226);
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
        }
        
        .save-btn {
          background: linear-gradient(135deg, #f39c12, #e67e22);
          color: white;
        }
        
        .save-btn:hover {
          background: linear-gradient(135deg, #e67e22, #d35400);
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
        }
        
        @media (max-width: 768px) {
          .toolbar {
            flex-direction: row;
            flex-wrap: wrap;
            justify-content: center;
            min-width: auto;
            padding: 12px;
            gap: 12px;
          }
          
          .templates-section {
            width: 100%;
          }
          
          .templates-grid {
            flex-direction: row;
            flex-wrap: wrap;
            justify-content: center;
          }
          
          .template-thumb {
            width: 80px;
          }
          
          .actions-section {
            flex-direction: row;
            padding-top: 12px;
            width: 100%;
            justify-content: center;
            border-top: 2px solid rgba(139, 94, 60, 0.2);
          }
          
          .action-btn {
            flex: 1;
            max-width: 150px;
          }
        }
      `}</style>
    </div>
  )
}

export default Toolbar
